import { BudgetData } from "./types";

export const amalfiCoastBudget: BudgetData = {
  tripId: "amalfi",
  totalBudget: 7000,
  totalSpent: 4850,
  totalRemaining: 2150,
  currency: "USD",
  percentageSpent: 69.3,
  averageDailySpend: 387.5,
  estimatedTotalSpend: 5500,
  categories: [
    {
      name: "TRANSPORT",
      label: "Transport",
      percentage: 35,
      color: "#001a33",
      amount: 2450,
      spent: 1380,
      remaining: 1070,
    },
    {
      name: "LODGING",
      label: "Lodging",
      percentage: 40,
      color: "#1a5f6f",
      amount: 2800,
      spent: 2705.5,
      remaining: 94.5,
    },
    {
      name: "FOOD",
      label: "Food",
      percentage: 15,
      color: "#6b4423",
      amount: 1050,
      spent: 375,
      remaining: 675,
    },
    {
      name: "ENTERTAINMENT",
      label: "Entertainment",
      percentage: 10,
      color: "#7dd3d3",
      amount: 700,
      spent: 390,
      remaining: 310,
    },
  ],
  transactions: [
    {
      id: "txn-1",
      tripId: "amalfi",
      description: "Dinner at Da Paolino",
      location: "Capri, Italy",
      date: "2024-06-14",
      amount: 248.0,
      currency: "USD",
      category: "FOOD",
      type: "EXPENSE",
      paymentMethod: "CARD",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "txn-2",
      tripId: "amalfi",
      description: "Private Boat Charter",
      location: "Positano Pier",
      date: "2024-06-13",
      amount: 1200.0,
      currency: "USD",
      category: "ENTERTAINMENT",
      type: "EXPENSE",
      paymentMethod: "CARD",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "txn-3",
      tripId: "amalfi",
      description: "Le Sirenuse Deposit",
      location: "Positano",
      date: "2024-06-12",
      amount: 3402.15,
      currency: "USD",
      category: "LODGING",
      type: "EXPENSE",
      paymentMethod: "CARD",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "txn-4",
      tripId: "amalfi",
      description: "Private Transfer from Naples",
      location: "NAP Airport",
      date: "2024-06-12",
      amount: 180.0,
      currency: "USD",
      category: "TRANSPORT",
      type: "EXPENSE",
      paymentMethod: "CARD",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export function getBudgetData(tripId: string): BudgetData | undefined {
  if (tripId === "amalfi") {
    return amalfiCoastBudget;
  }
  return undefined;
}
